/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.usuario;

import DataAccessObject.UsuarioValueObject;
import controller.UsuarioController;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JCheckBox;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author leona
 */
public class Editar extends javax.swing.JDialog {

    /**
     * Creates new form EditarUsuario
     */
    public Editar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    private boolean dadosValidos = false;

    public void preencherCampos(UsuarioValueObject usuario){
        txtNome.setText(usuario.getNome());
        txtUsuario.setText(usuario.getUsuario());
        txtSenha.setText(usuario.getSenha());
        txtConfirmarSenha.setText(usuario.getSenha());
        checkMaster.setSelected(usuario.isMaster());
    }
    
    public JCheckBox getCheckMaster() {
        return checkMaster;
    }

    public JTextField getTxtNome() {
        return txtNome;
    }

    public JPasswordField getTxtSenha() {
        return txtSenha;
    }

    public JTextField getTxtUsuario() {
        return txtUsuario;
    }

    private boolean validarNome(){
        return UsuarioController.validarNome(txtNome.getText());
    }
    
    private boolean validarUsuario(){
        return UsuarioController.validarUsuario(txtUsuario.getText());
    }
    
    private boolean validarSenha(){
        return UsuarioController.validarSenha(txtSenha.getPassword());
    }
    
    private boolean verificarSenha(){
        return UsuarioController.verificarSenha(txtSenha.getPassword(), txtConfirmarSenha.getPassword());
    }
    
    public boolean validar(){
        return (verificarSenha() && validarNome() && validarUsuario()&& validarSenha() && dadosValidos);
    }
    
    private void validarEFechar(){
        boolean valido = true;
        if(UsuarioController.validarNome(txtNome.getText())){
            verificacaoNome.setBackground(Color.green);
        }
        else{
            verificacaoNome.setBackground(Color.red);
            txtNome.requestFocusInWindow();
            valido = false;
        }
        if(UsuarioController.validarUsuario(txtUsuario.getText())){
            verificacaoUsuario.setBackground(Color.green);
        }
        else{
            verificacaoUsuario.setBackground(Color.red);
            txtUsuario.requestFocusInWindow();
            valido = false;
        }
        if(UsuarioController.validarSenha(txtSenha.getPassword())){
            verificacaoSenha.setBackground(Color.green);
        }
        else{
            verificacaoSenha.setBackground(Color.red);
            txtSenha.requestFocusInWindow();
            valido = false;
        }
        if(UsuarioController.verificarSenha(txtSenha.getPassword(), txtConfirmarSenha.getPassword())){
            verificacaoConfirmacaoSenha.setBackground(Color.green);
        }
        else{
            verificacaoConfirmacaoSenha.setBackground(Color.red);
            txtSenha.requestFocusInWindow();
            valido = false;
        }
        if(valido){
            dadosValidos = true;
            dispose();
        }
    }
    
    private void enterCampoNome(){
        validarEFechar();
        if(validarNome()){
            txtUsuario.requestFocusInWindow();
        }
    }
    
    private void enterCampoUsuario(){
        validarEFechar();
        if(validarUsuario()){
            txtSenha.requestFocusInWindow();
        }
    }
    
    private void enterCampoSenha(){
        validarEFechar();
        if(validarSenha()){
            txtConfirmarSenha.requestFocusInWindow();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        txtUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        txtConfirmarSenha = new javax.swing.JPasswordField();
        checkMaster = new javax.swing.JCheckBox();
        btnSalvar = new javax.swing.JButton();
        verificacaoNome = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        verificacaoUsuario = new javax.swing.JPanel();
        txtNome = new javax.swing.JTextField();
        verificacaoSenha = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        verificacaoConfirmacaoSenha = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyReleased(evt);
            }
        });

        jLabel4.setText("Senha:");

        jLabel5.setText("Confirmar senha:");

        txtSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSenhaKeyReleased(evt);
            }
        });

        txtConfirmarSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtConfirmarSenhaKeyReleased(evt);
            }
        });

        checkMaster.setText("Usuário Master");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout verificacaoNomeLayout = new javax.swing.GroupLayout(verificacaoNome);
        verificacaoNome.setLayout(verificacaoNomeLayout);
        verificacaoNomeLayout.setHorizontalGroup(
            verificacaoNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        verificacaoNomeLayout.setVerticalGroup(
            verificacaoNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        jLabel2.setText("Nome:");

        javax.swing.GroupLayout verificacaoUsuarioLayout = new javax.swing.GroupLayout(verificacaoUsuario);
        verificacaoUsuario.setLayout(verificacaoUsuarioLayout);
        verificacaoUsuarioLayout.setHorizontalGroup(
            verificacaoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        verificacaoUsuarioLayout.setVerticalGroup(
            verificacaoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        txtNome.setToolTipText("");
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout verificacaoSenhaLayout = new javax.swing.GroupLayout(verificacaoSenha);
        verificacaoSenha.setLayout(verificacaoSenhaLayout);
        verificacaoSenhaLayout.setHorizontalGroup(
            verificacaoSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        verificacaoSenhaLayout.setVerticalGroup(
            verificacaoSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        jLabel3.setText("Usuário:");

        javax.swing.GroupLayout verificacaoConfirmacaoSenhaLayout = new javax.swing.GroupLayout(verificacaoConfirmacaoSenha);
        verificacaoConfirmacaoSenha.setLayout(verificacaoConfirmacaoSenhaLayout);
        verificacaoConfirmacaoSenhaLayout.setHorizontalGroup(
            verificacaoConfirmacaoSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        verificacaoConfirmacaoSenhaLayout.setVerticalGroup(
            verificacaoConfirmacaoSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkMaster)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 253, Short.MAX_VALUE)
                        .addComponent(btnSalvar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtConfirmarSenha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                            .addComponent(txtSenha, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(verificacaoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(verificacaoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(verificacaoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(verificacaoConfirmacaoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verificacaoNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verificacaoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verificacaoSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verificacaoConfirmacaoSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkMaster)
                    .addComponent(btnSalvar)))
        );

        pack();
    }// </editor-fold>                        

    private void txtUsuarioKeyReleased(java.awt.event.KeyEvent evt) {                                       
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            enterCampoUsuario();
        }
    }                                      

    private void txtSenhaKeyReleased(java.awt.event.KeyEvent evt) {                                     
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            enterCampoSenha();
        }
    }                                    

    private void txtConfirmarSenhaKeyReleased(java.awt.event.KeyEvent evt) {                                              
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            validarEFechar();
        }
    }                                             

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        validarEFechar();
    }                                         

    private void txtNomeKeyReleased(java.awt.event.KeyEvent evt) {                                    
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            enterCampoNome();
        }
    }                                   

    /**
     * @param usuarioValueObject
     * @return 
     */
    public static UsuarioValueObject inicio(UsuarioValueObject usuarioValueObject) {
        Editar dialog = new Editar(new javax.swing.JFrame(), true);
        dialog.setLocationRelativeTo(null);
        dialog.preencherCampos(usuarioValueObject);
        dialog.setVisible(true);
        if(dialog.validar()){
            return new UsuarioValueObject(
                                        dialog.getTxtNome().getText(),//nome
                                        dialog.getTxtUsuario().getText(),//usuário
                                        String.copyValueOf(dialog.getTxtSenha().getPassword()),//senha
                                        dialog.getCheckMaster().isSelected()//usuário master
            );   
        }
        return null;
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnSalvar;
    private javax.swing.JCheckBox checkMaster;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField txtConfirmarSenha;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JPanel verificacaoConfirmacaoSenha;
    private javax.swing.JPanel verificacaoNome;
    private javax.swing.JPanel verificacaoSenha;
    private javax.swing.JPanel verificacaoUsuario;
    // End of variables declaration                   
}
