/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controller;

/**
 *
 * @author leona
 */
public enum Etapas {
    LOGIN, LOGIN_MASTER, ABRIR_FORMULARIO_PRINCIPAL, CARREGAR_CONTEUDO_FORMULARIO_PRINCIPAL, ABRIR_FORMULARIO_USUARIOS,
    ABRIR_FORMULARIO_CADASTRO_USUARIOS, ABRIR_FORMULARIO_EDITA_USUARIOS, CONFIRMAR_EXCLUSAO_USUARIO, EXCLUIR_USUARIO,
    MOSTRAR_MENSAGEM_SUCESSO_EXCLIUR, MOSTRAR_MENSAGEM_ERRO_EXCLIUR,
    ABRIR_FORMULARIO_NAO_CONFORMIDADES, ABRIR_FORMULARIO_CADASTRO_NAO_CONFORMIDADE,
    ABRIR_FORMULARIO_SETORES, ABRIR_FORMULARIO_RESPONSAVEL, SAIR;
}
